WITH CUSTOMERS AS (
    SELECT * FROM {{ ref('stg_customers') }}
),

ORDERS AS (
    SELECT * FROM {{ ref('stg_orders') }}
),

PAYMENTS AS (
    SELECT * FROM {{ ref('stg_payments') }}
),

CUSTOMER_ORDERS AS (
    SELECT
        CUSTOMER_ID,
        min(ORDER_DATE) AS FIRST_ORDER,
        max(ORDER_DATE) AS MOST_RECENT_ORDER,
        count(ORDER_ID) AS NUMBER_OF_ORDERS
    FROM ORDERS
    GROUP BY CUSTOMER_ID
),

CUSTOMER_PAYMENTS AS (
    SELECT
        ORDERS.CUSTOMER_ID,
        sum(PAYMENTS.AMOUNT) AS TOTAL_AMOUNT
    FROM PAYMENTS
    LEFT JOIN ORDERS
        ON
            PAYMENTS.ORDER_ID = ORDERS.ORDER_ID
    GROUP BY ORDERS.CUSTOMER_ID
),

FINAL AS (
    SELECT
        CUSTOMERS.CUSTOMER_ID,
        CUSTOMERS.FIRST_NAME,
        CUSTOMERS.LAST_NAME,
        CUSTOMER_ORDERS.FIRST_ORDER,
        CUSTOMER_ORDERS.MOST_RECENT_ORDER,
        CUSTOMER_ORDERS.NUMBER_OF_ORDERS,
        CUSTOMER_PAYMENTS.TOTAL_AMOUNT AS CUSTOMER_LIFETIME_VALUE
    FROM CUSTOMERS
    LEFT JOIN CUSTOMER_ORDERS
        ON CUSTOMERS.CUSTOMER_ID = CUSTOMER_ORDERS.CUSTOMER_ID
    LEFT JOIN CUSTOMER_PAYMENTS
        ON CUSTOMERS.CUSTOMER_ID = CUSTOMER_PAYMENTS.CUSTOMER_ID
)

SELECT * FROM FINAL
